services:
 azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    volumes:
      - azurite-data:/data/azurite
    environment:
      AZURITE_ACCOUNTS: "local"
      AZURITE_BLOB_HOST: "0.0.0.0"
      AZURITE_BLOB_PORT: 10000
      AZURITE_QUEUE_HOST: "0.0.0.0"
      AZURITE_QUEUE_PORT: 10001
      AZURITE_TABLE_HOST: "0.0.0.0"
      AZURITE_TABLE_PORT: 10002
      AZURITE_BLOB_CORS: "corsRules=[{allowedOrigins:['*'],allowedMethods:['GET','PUT','POST','DELETE','OPTIONS'],allowedHeaders:['*'],exposedHeaders:['*'],maxAgeInSeconds:3600}]"
 postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: andos
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
 azurite-data:
 postgres-data: